from xhtml2pdf import pisa
import io
import base64

def clean_text(text):
    return str(text).encode('latin-1', 'ignore').decode('latin-1')

def generate_executive_pdf(mad_score, verdict, insights, fig, hit_list_df):

    img_bytes = fig.to_image(format='png', engine='kaleido', width=800, height=400)
    encoded_img = base64.b64encode(img_bytes).decode('utf-8')
    img_tag = f"<img src='data:image/png;base64,{encoded_img}' style='width: 100%; margin-top: 20px;'>"

    table_html = """
    <table>
        <tr>
            <th>Date</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Risk Status</th>
        </tr>
    """
    for index, row in hit_list_df.head(20).iterrows():

        risk_style = "color: #DC2626; font-weight: bold;" if row['risk_score'] >= 8 else "color: #D97706;"
        table_html += f"""
        <tr>
            <td>{row['date']}</td>
            <td>{clean_text(row['category'])}</td>
            <td><strong>${row['amount']:,.2f}</strong></td>
            <td style="{risk_style}">{clean_text(row['status'])}</td>
        </tr>
        """
    table_html += "</table>"

    insights_html = "".join([f"<li>{clean_text(i)}</li>" for i in insights])

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @page {{ size: a4 portrait; margin: 2cm; }}
            body {{ font-family: Helvetica, Arial, sans-serif; color: #1F2937; }}
            
            /* Modern Header */
            .header {{ text-align: center; border-bottom: 3px solid #2563EB; padding-bottom: 10px; margin-bottom: 30px; }}
            .header h1 {{ margin: 0; color: #1E3A8A; font-size: 28px; }}
            .header p {{ margin: 5px 0 0 0; color: #6B7280; font-size: 14px; }}
            
            /* Summary Card */
            .summary-box {{ background-color: #F3F4F6; padding: 20px; border-radius: 8px; border-left: 5px solid #2563EB; }}
            .summary-box h2 {{ margin-top: 0; font-size: 18px; color: #111827; }}
            .verdict {{ font-size: 16px; font-weight: bold; color: #DC2626; margin-top: 10px; }}
            
            /* Table Styling */
            h2 {{ color: #1E3A8A; font-size: 20px; margin-top: 40px; border-bottom: 1px solid #E5E7EB; padding-bottom: 5px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 12px; }}
            th {{ background-color: #2563EB; color: #ffffff; padding: 10px; text-align: left; font-weight: bold; }}
            td {{ padding: 10px; border-bottom: 1px solid #E5E7EB; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>PennyWise Forensic Report</h1>
            <p>Automated Ledger Intelligence & Anomaly Detection</p>
        </div>

        <div class="summary-box">
            <h2>Systemic Integrity Check</h2>
            <p><strong>MAD Score:</strong> {mad_score:.2f}</p>
            <p class="verdict">{clean_text(verdict)}</p>
            <ul style="margin-bottom: 0;">
                {insights_html}
            </ul>
        </div>

        {img_tag}

        <pdf:nextpage />

        <h2>Critical Anomalies Detected</h2>
        {table_html}

        <p style="text-align: center; font-size: 10px; color: #9CA3AF; margin-top: 50px;">
            Generated by PennyWise Autonomous Engine | Confidential
        </p>
    </body>
    </html>
    """

    pdf_file = io.BytesIO()
    pisa.CreatePDF(io.StringIO(html_content), dest=pdf_file)

    return pdf_file.getvalue()
